export const dom = {
    loginScreen: document.getElementById("login-screen"),
    appScreen: document.getElementById("app-screen"),
    tradingStatusPill: document.getElementById("trading-status-pill"),
    tradingStatusLabel: document.getElementById("trading-status-label"),
    sessionControlBar: document.getElementById("session-control-bar"),
    loginForm: document.getElementById("login-form"),
    errorMessage: document.getElementById("login-error"),
    logoutButton: document.getElementById("logout-button"),
    loggedInUser: document.getElementById("logged-in-user"),

    usersTableBody: document.getElementById("users-table-body"),
    noUsersMessage: document.getElementById("no-users-message"),
    addUserButton: document.getElementById("add-user-button"),
    userModal: document.getElementById("user-modal"),
    userModalTitle: document.getElementById("user-modal-title"),
    userForm: document.getElementById("user-form"),
    editingUserIdInput: document.getElementById("editing-user-id"),
    userUsernameInput: document.getElementById("user-username"),
    userPasswordInput: document.getElementById("user-password"),
    userPasswordHelp: document.getElementById("user-password-help"),
    userRoleInput: document.getElementById("user-role"),
    userActiveInput: document.getElementById("user-active"),
    userFormError: document.getElementById("user-form-error"),
    closeUserModalButton: document.getElementById("close-user-modal"),
    cancelUserButton: document.getElementById("cancel-user-button"),

    navigationButtons: document.querySelectorAll(".nav-button"),
    appSections: document.querySelectorAll(".app-section"),

    trainingModeBanner: document.getElementById("training-mode-banner"),

    discountModal: document.getElementById("discount-modal"),
    discountForm: document.getElementById("discount-form"),
    discountPercentInput: document.getElementById("discount-percent"),
    discountPinInput: document.getElementById("discount-pin"),
    discountFormError: document.getElementById("discount-form-error"),
    closeDiscountModalButton: document.getElementById("close-discount-modal"),
    cancelDiscountButton: document.getElementById("cancel-discount-button"),
    removeDiscountButton: document.getElementById("remove-discount-button"),

    productGrid: document.getElementById("product-grid"),
    orderItemsContainer: document.getElementById("order-items"),
    emptyOrderMessage: document.getElementById("empty-order"),
    orderSubtotalRow: document.getElementById("order-subtotal-row"),
    orderSubtotal: document.getElementById("order-subtotal"),
    orderDiscountRow: document.getElementById("order-discount-row"),
    orderDiscountLabel: document.getElementById("order-discount-label"),
    orderDiscount: document.getElementById("order-discount"),
    orderTotal: document.getElementById("order-total"),
    orderOptionsButton: document.getElementById("order-options-button"),
    clearOrderButton: document.getElementById("clear-order-button"),
    completeSaleButton: document.getElementById("complete-sale-button"),
    orderNumberDisplay: document.getElementById("order-number"),
    sessionStatusText: document.getElementById("session-status-text"),
    startSessionButton: document.getElementById("start-session-button"),
    cashOffSessionButton: document.getElementById("cash-off-session-button"),

    productsTableBody: document.getElementById("products-table-body"),
    noProductsMessage: document.getElementById("no-products-message"),
    addProductButton: document.getElementById("add-product-button"),
    productModal: document.getElementById("product-modal"),
    productModalTitle: document.getElementById("product-modal-title"),
    productForm: document.getElementById("product-form"),
    editingProductIdInput: document.getElementById("editing-product-id"),
    editingProductGroupIdInput: document.getElementById("editing-product-group-id"),
    productNameInput: document.getElementById("product-name"),
    productPriceInput: document.getElementById("product-price"),
    productTileColorInput: document.getElementById("product-tile-color"),
    productStockInput: document.getElementById("product-stock"),
    singleStockGroup: document.getElementById("single-stock-group"),
    productHasVariantsInput: document.getElementById("product-has-variants"),
    productVariantsSection: document.getElementById("product-variants-section"),
    variantRows: document.getElementById("variant-rows"),
    addVariantButton: document.getElementById("add-variant-button"),
    productFormError: document.getElementById("product-form-error"),
    closeProductModalButton: document.getElementById("close-product-modal"),
    cancelProductButton: document.getElementById("cancel-product-button"),

    variantModal: document.getElementById("variant-modal"),
    variantModalTitle: document.getElementById("variant-modal-title"),
    variantModalPrice: document.getElementById("variant-modal-price"),
    variantOptions: document.getElementById("variant-options"),
    closeVariantModalButton: document.getElementById("close-variant-modal"),
    cancelVariantButton: document.getElementById("cancel-variant-button"),

    todayReportButton: document.getElementById("today-report-button"),
    reportStartDate: document.getElementById("report-start-date"),
    reportEndDate: document.getElementById("report-end-date"),
    applyReportRangeButton: document.getElementById("apply-report-range-button"),
    reportSessionButtons: document.getElementById("report-session-buttons"),
    reportRevenue: document.getElementById("report-revenue"),
    reportDiscounts: document.getElementById("report-discounts"),
    reportItemsSold: document.getElementById("report-items-sold"),
    reportTransactionsCount: document.getElementById("report-transactions-count"),
    reportProductsSold: document.getElementById("report-products-sold"),
    toggleTransactionsButton: document.getElementById("toggle-transactions-button"),
    reportTransactions: document.getElementById("report-transactions")
};
