export const dom = {
    loginScreen: document.getElementById("login-screen"),
    appScreen: document.getElementById("app-screen"),
    tradingStatusPill: document.getElementById("trading-status-pill"),
    tradingStatusLabel: document.getElementById("trading-status-label"),
    sessionControlBar: document.getElementById("session-control-bar"),
    loginForm: document.getElementById("login-form"),
    errorMessage: document.getElementById("login-error"),
    logoutButton: document.getElementById("logout-button"),
    loggedInUser: document.getElementById("logged-in-user"),

    usersTableBody: document.getElementById("users-table-body"),
    noUsersMessage: document.getElementById("no-users-message"),
    addUserButton: document.getElementById("add-user-button"),
    userModal: document.getElementById("user-modal"),
    userModalTitle: document.getElementById("user-modal-title"),
    userForm: document.getElementById("user-form"),
    editingUserIdInput: document.getElementById("editing-user-id"),
    userUsernameInput: document.getElementById("user-username"),
    userPasswordInput: document.getElementById("user-password"),
    userPasswordHelp: document.getElementById("user-password-help"),
    userRoleInput: document.getElementById("user-role"),
    userActiveInput: document.getElementById("user-active"),
    userFormError: document.getElementById("user-form-error"),
    closeUserModalButton: document.getElementById("close-user-modal"),
    cancelUserButton: document.getElementById("cancel-user-button"),

    navigationButtons: document.querySelectorAll(".nav-button"),
    appSections: document.querySelectorAll(".app-section"),

    trainingModeBanner: document.getElementById("training-mode-banner"),

    productGrid: document.getElementById("product-grid"),
    orderItemsContainer: document.getElementById("order-items"),
    emptyOrderMessage: document.getElementById("empty-order"),
    orderTotal: document.getElementById("order-total"),
    clearOrderButton: document.getElementById("clear-order-button"),
    completeSaleButton: document.getElementById("complete-sale-button"),
    orderNumberDisplay: document.getElementById("order-number"),
    sessionStatusText: document.getElementById("session-status-text"),
    startSessionButton: document.getElementById("start-session-button"),
    cashOffSessionButton: document.getElementById("cash-off-session-button"),

    productsTableBody: document.getElementById("products-table-body"),
    noProductsMessage: document.getElementById("no-products-message"),
    addProductButton: document.getElementById("add-product-button"),
    productModal: document.getElementById("product-modal"),
    productModalTitle: document.getElementById("product-modal-title"),
    productForm: document.getElementById("product-form"),
    editingProductIdInput: document.getElementById("editing-product-id"),
    productNameInput: document.getElementById("product-name"),
    productPriceInput: document.getElementById("product-price"),
    productStockInput: document.getElementById("product-stock"),
    productFormError: document.getElementById("product-form-error"),
    closeProductModalButton: document.getElementById("close-product-modal"),
    cancelProductButton: document.getElementById("cancel-product-button"),

    todayReportButton: document.getElementById("today-report-button"),
    reportStartDate: document.getElementById("report-start-date"),
    reportEndDate: document.getElementById("report-end-date"),
    applyReportRangeButton: document.getElementById("apply-report-range-button"),
    reportSessionButtons: document.getElementById("report-session-buttons"),
    reportRevenue: document.getElementById("report-revenue"),
    reportItemsSold: document.getElementById("report-items-sold"),
    reportTransactionsCount: document.getElementById("report-transactions-count"),
    reportProductsSold: document.getElementById("report-products-sold"),
    toggleTransactionsButton: document.getElementById("toggle-transactions-button"),
    reportTransactions: document.getElementById("report-transactions")
};
